# Form implementation generated from reading ui file 'Function1.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pandas as pd
import numpy as np
import sys
import PIL
sys.path.append("..")
from PGE_Model import Heatmap
from PGE_Model import Relation

class Ui_Form1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1032, 781)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1031, 781))
        self.scrollArea.setStyleSheet("border:transparent;\n"
"background-color:white;\n"
"QScrollBar {height:0px;width:0px;}")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1031, 3820))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(871, 3820))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(30, 20, 161, 51))
        self.label.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("font-size:40px;font:bold;")
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setGeometry(QtCore.QRect(30, 80, 971, 1))
        self.line.setStyleSheet("background-color:rgb(230,230,230);\n"
"max-height:5px;")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.HeatmapLable = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.HeatmapLable.setGeometry(QtCore.QRect(70, 119, 891, 801))
        self.HeatmapLable.setStyleSheet("background-color:rgb(245,245,245);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;")
        self.HeatmapLable.setObjectName("HeatmapLable")
        self.PGEHTMTEXT = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.PGEHTMTEXT.setGeometry(QtCore.QRect(460, 930, 131, 21))
        self.PGEHTMTEXT.setObjectName("PGEHTMTEXT")
        self.SAHeatmapLable = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.SAHeatmapLable.setGeometry(QtCore.QRect(30, 970, 461, 421))
        self.SAHeatmapLable.setStyleSheet("background-color:rgb(245,245,245);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;")
        self.SAHeatmapLable.setObjectName("SAHeatmapLable")
        self.DHeatmapLable = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.DHeatmapLable.setGeometry(QtCore.QRect(540, 970, 461, 421))
        self.DHeatmapLable.setStyleSheet("background-color:rgb(245,245,245);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;")
        self.DHeatmapLable.setObjectName("DHeatmapLable")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(710, 1400, 161, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(190, 1400, 161, 16))
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setGeometry(QtCore.QRect(30, 1430, 971, 1))
        self.line_2.setStyleSheet("background-color:rgb(230,230,230);\n"
"max-height:5px;")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.PGEAnalysis = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.PGEAnalysis.setGeometry(QtCore.QRect(30, 1450, 250, 250))
        self.PGEAnalysis.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.PGEAnalysis.setObjectName("PGEAnalysis")
        self.PRAnalysis = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.PRAnalysis.setGeometry(QtCore.QRect(750, 1450, 250, 250))
        self.PRAnalysis.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.PRAnalysis.setObjectName("PRAnalysis")
        self.SAAnalysis = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.SAAnalysis.setGeometry(QtCore.QRect(390, 1450, 250, 250))
        self.SAAnalysis.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.SAAnalysis.setObjectName("SAAnalysis")
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setGeometry(QtCore.QRect(30, 1730, 971, 1))
        self.line_3.setStyleSheet("background-color:rgb(230,230,230);\n"
"max-height:5px;")
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.PGEAPic = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.PGEAPic.setGeometry(QtCore.QRect(30, 1760, 481, 311))
        self.PGEAPic.setStyleSheet("border:2px solid rgb(85,179,236);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);")
        self.PGEAPic.setObjectName("PGEAPic")
        self.PGEAPicA = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.PGEAPicA.setGeometry(QtCore.QRect(570, 1860, 401, 111))
        self.PGEAPicA.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.PGEAPicA.setObjectName("PGEAPicA")
        self.SAAPic = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.SAAPic.setGeometry(QtCore.QRect(510, 2100, 481, 311))
        self.SAAPic.setStyleSheet("border:2px solid rgb(85,179,236);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);")
        self.SAAPic.setObjectName("SAAPic")
        self.SAAPicA = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.SAAPicA.setGeometry(QtCore.QRect(50, 2200, 401, 111))
        self.SAAPicA.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.SAAPicA.setObjectName("SAAPicA")
        self.PRAPic = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.PRAPic.setGeometry(QtCore.QRect(30, 2440, 481, 311))
        self.PRAPic.setStyleSheet("border:2px solid rgb(85,179,236);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"")
        self.PRAPic.setObjectName("PRAPic")
        self.SPRAPicA = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.SPRAPicA.setGeometry(QtCore.QRect(560, 2530, 401, 111))
        self.SPRAPicA.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.SPRAPicA.setObjectName("SPRAPicA")
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setGeometry(QtCore.QRect(30, 2780, 971, 1))
        self.line_4.setStyleSheet("background-color:rgb(230,230,230);\n"
"max-height:5px;")
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(30, 2810, 121, 31))
        self.label_4.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font-size:30px;font:bold;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(30, 3130, 111, 16))
        self.label_5.setObjectName("label_5")
        self.LRShowPic = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.LRShowPic.setGeometry(QtCore.QRect(30, 2860, 441, 241))
        self.LRShowPic.setStyleSheet("border:1px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"")
        self.LRShowPic.setText("")
        self.LRShowPic.setObjectName("LRShowPic")
        self.RFShowPic = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.RFShowPic.setGeometry(QtCore.QRect(599, 2869, 391, 231))
        self.RFShowPic.setStyleSheet("border-image: url(./ICON/6.png);\n"
"\n"
"")
        self.RFShowPic.setText("")
        self.RFShowPic.setObjectName("RFShowPic")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(570, 3130, 131, 16))
        self.label_8.setObjectName("label_8")
        self.RF = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.RF.setGeometry(QtCore.QRect(570, 3170, 401, 71))
        self.RF.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);\n"
"")
        self.RF.setObjectName("RF")
        self.LR = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.LR.setGeometry(QtCore.QRect(30, 3170, 401, 71))
        self.LR.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.LR.setObjectName("LR")
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setGeometry(QtCore.QRect(30, 3280, 971, 1))
        self.line_5.setStyleSheet("background-color:rgb(230,230,230);\n"
"max-height:5px;")
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(30, 3310, 121, 31))
        self.label_6.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font-size:30px;font:bold;")
        self.label_6.setObjectName("label_6")
        self.CJYCJJ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.CJYCJJ.setGeometry(QtCore.QRect(180, 3380, 271, 141))
        self.CJYCJJ.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.CJYCJJ.setObjectName("CJYCJJ")
        self.KYFXJJ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.KYFXJJ.setGeometry(QtCore.QRect(710, 3380, 271, 141))
        self.KYFXJJ.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.KYFXJJ.setObjectName("KYFXJJ")
        self.CGFXJJ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.CGFXJJ.setGeometry(QtCore.QRect(180, 3600, 271, 141))
        self.CGFXJJ.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.CGFXJJ.setObjectName("CGFXJJ")
        self.BSFXJJ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.BSFXJJ.setGeometry(QtCore.QRect(710, 3600, 271, 141))
        self.BSFXJJ.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.BSFXJJ.setObjectName("BSFXJJ")
        self.KYFX = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.KYFX.setGeometry(QtCore.QRect(560, 3400, 101, 101))
        self.KYFX.setStyleSheet("background-color:rgb(81,170,236);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;\n"
"")
        self.KYFX.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.KYFX.setObjectName("KYFX")
        self.BSFX = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.BSFX.setGeometry(QtCore.QRect(560, 3620, 101, 101))
        self.BSFX.setStyleSheet("background-color:rgb(81,170,236);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;\n"
"")
        self.BSFX.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BSFX.setObjectName("BSFX")
        self.CGFX = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.CGFX.setGeometry(QtCore.QRect(30, 3620, 101, 101))
        self.CGFX.setStyleSheet("background-color:rgb(81,170,236);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;\n"
"")
        self.CGFX.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CGFX.setObjectName("CGFX")
        self.CJYC = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.CJYC.setGeometry(QtCore.QRect(30, 3400, 101, 101))
        self.CJYC.setStyleSheet("background-color:rgb(81,170,236);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;\n"
"")
        self.CJYC.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CJYC.setObjectName("CJYC")
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_6.setGeometry(QtCore.QRect(180, 3560, 271, 1))
        self.line_6.setStyleSheet("background-color:rgb(230,230,230);\n"
"max-height:5px;")
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_7.setGeometry(QtCore.QRect(710, 3560, 271, 1))
        self.line_7.setStyleSheet("background-color:rgb(230,230,230);\n"
"max-height:5px;")
        self.line_7.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_8.setGeometry(QtCore.QRect(30, 3780, 941, 1))
        self.line_8.setStyleSheet("background-color:rgb(230,230,230);\n"
"max-height:5px;")
        self.line_8.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_8.setObjectName("line_8")
        self.LRShowPic_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.LRShowPic_2.setGeometry(QtCore.QRect(560, 2860, 441, 241))
        self.LRShowPic_2.setStyleSheet("border:1px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"")
        self.LRShowPic_2.setText("")
        self.LRShowPic_2.setObjectName("LRShowPic_2")
        self.RFShowPic_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.RFShowPic_2.setGeometry(QtCore.QRect(50, 2870, 401, 221))
        self.RFShowPic_2.setStyleSheet("border-image: url(./ICON/7.png);\n"
"\n"
"")
        self.RFShowPic_2.setText("")
        self.RFShowPic_2.setObjectName("RFShowPic_2")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(30, 90, 91, 16))
        self.label_7.setStyleSheet("color:rgb(85,179,236);font-size:10px;background-color:transparent;")
        self.label_7.setObjectName("label_7")
        self.LRShowPic_2.raise_()
        self.label.raise_()
        self.line.raise_()
        self.HeatmapLable.raise_()
        self.PGEHTMTEXT.raise_()
        self.SAHeatmapLable.raise_()
        self.DHeatmapLable.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.line_2.raise_()
        self.PGEAnalysis.raise_()
        self.PRAnalysis.raise_()
        self.SAAnalysis.raise_()
        self.line_3.raise_()
        self.PGEAPic.raise_()
        self.PGEAPicA.raise_()
        self.SAAPic.raise_()
        self.SAAPicA.raise_()
        self.PRAPic.raise_()
        self.SPRAPicA.raise_()
        self.line_4.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.LRShowPic.raise_()
        self.label_8.raise_()
        self.RF.raise_()
        self.LR.raise_()
        self.line_5.raise_()
        self.label_6.raise_()
        self.CJYCJJ.raise_()
        self.KYFXJJ.raise_()
        self.CGFXJJ.raise_()
        self.BSFXJJ.raise_()
        self.KYFX.raise_()
        self.BSFX.raise_()
        self.CGFX.raise_()
        self.CJYC.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.line_8.raise_()
        self.RFShowPic.raise_()
        self.RFShowPic_2.raise_()
        self.label_7.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "分析展示"))
        self.HeatmapLable.setText(_translate("Form", "考研热力图"))
        self.PGEHTMTEXT.setText(_translate("Form", "考研相关要素热力图"))
        self.SAHeatmapLable.setText(_translate("Form", "出国留学热力图"))
        self.DHeatmapLable.setText(_translate("Form", "直博保研热力图"))
        self.label_2.setText(_translate("Form", "直博保研相关要素热力图"))
        self.label_3.setText(_translate("Form", "出国留学相关要素热力图"))
        self.PGEAnalysis.setText(_translate("Form", "考研相关要素热力图分析\n"
"\n"
"最有可能影响上岸的特征是考研总分\n"
"数学分数、超过国家线及院线的分数\n"
"\n"
"影响相对较小的特征是本科院校级别\n"
"本科的平均绩点、四六级成绩"))
        self.PRAnalysis.setText(_translate("Form", "保研直博相关要素热力图分析\n"
"\n"
"最有可能影响保送的特征是学校等级\n"
"研习经历\n"
"\n"
"影响相对较小的特征是自身意愿和是\n"
"否有学术产物"))
        self.SAAnalysis.setText(_translate("Form", "留学相关要素热力图分析\n"
"\n"
"最有可能影响留学的特征是GRE\n"
"平均绩点、TOEFL成绩\n"
"\n"
"影响相对较小的特征是推荐信力度\n"
"自身意愿、是否有学术成就"))
        self.PGEAPic.setText(_translate("Form", "考研最相关要素点状图"))
        self.PGEAPicA.setText(_translate("Form", "数学分数在考研总分的地位至关重要\n"
"\n"
"数学分数越高，总分越高，两者相关性很大"))
        self.SAAPic.setText(_translate("Form", "出国最相关要素点状图"))
        self.SAAPicA.setText(_translate("Form", "留学深造方面\n"
"\n"
"GPA平均绩点越高，留学深造的意愿更强"))
        self.PRAPic.setText(_translate("Form", "直博最相关要素点状图"))
        self.SPRAPicA.setText(_translate("Form", "直博保研方面\n"
"\n"
"大多数保送成功的学生都有做项目和实习的经验"))
        self.label_4.setText(_translate("Form", "算法展示"))
        self.label_5.setText(_translate("Form", "线性回归算法"))
        self.label_8.setText(_translate("Form", "随机森林分类算法"))
        self.RF.setText(_translate("Form", "随机森林最早由Leo Breiman和Adele Cutler提出\n"
"指的是利用多棵树对样本进行训练并预测的一种分类器"))
        self.LR.setText(_translate("Form", "线性回归是利用数理统计中回归分析\n"
"来确定两种或两种以上变量间相互依赖的定量关系的一种分析方法"))
        self.label_6.setText(_translate("Form", "功能简介"))
        self.CJYCJJ.setText(_translate("Form", "成绩预测功能简介\n"
"\n"
"通过输入与预测科目相关的分数\n"
"使用线性回归模型结合数据库样本进行预测"))
        self.KYFXJJ.setText(_translate("Form", "考研分析功能简介\n"
"\n"
"展示分析与考研紧密相关的一些特征及关系\n"
"使用随机森林分类模型结合分数线等基本\n"
"信息进行上岸预测"))
        self.CGFXJJ.setText(_translate("Form", "留学分析功能简介\n"
"\n"
"展示分析与留学紧密相关的一些特征及关系\n"
"使用随机森林分类模型结合GPA等基本\n"
"信息对是否能够取得offer进行预测"))
        self.BSFXJJ.setText(_translate("Form", "保送分析功能简介\n"
"\n"
"展示分析与直博保研紧密相关的一些基本特征及关系\n"
"使用随机森林分类模型结合当前绩点等基本\n"
"信息对是否能够保送进行预测"))
        self.KYFX.setText(_translate("Form", "考研分析 "))
        self.BSFX.setText(_translate("Form", "保送分析 "))
        self.CGFX.setText(_translate("Form", "留学分析 "))
        self.CJYC.setText(_translate("Form", "成绩预测 "))
        self.label_7.setText(_translate("Form", "热力图"))
        self.plot()
    def plot(self):
            #print('1')
            dfPGE = pd.read_csv("/Users/reeno/Documents/Achievement_Analysis/Score/WPGE_Ver1.32.csv", sep =",")
            dfSA = pd.read_csv('/Users/reeno/Documents/Achievement_Analysis/score/Admission_Predict_Ver1.1.csv',sep=',')
            dfPR = pd.read_csv('/Users/reeno/Documents/Achievement_Analysis/score/WSDPR_Ver1.1.csv',sep=',')

            image = Heatmap.Draw_HeatMap(dfPGE)
            image_PGEAPic = Relation.Relation_btw_Math_and_Score(dfPGE)
            image_SAHeatMap = Heatmap.Draw_HeatMap(dfSA)
            image_PRHeatMap = Heatmap.Draw_HeatMap(dfPR)
            image_SAAPic = Relation.Relation_btw_SOP_and_GPA(dfSA)
            image_PRAPic = Relation.Relation_btw_SUC_and_Res(dfPR)

            Qimg_SAHeatMap = image_SAHeatMap.toqimage()#转换成qimage嵌入qt
            Qimg = image.toqimage()
            Qimg_PGEAPic = image_PGEAPic.toqimage()
            Qimg_PRHeatMap = image_PRHeatMap.toqimage()
            Qimg_SAAPic = image_SAAPic.toqimage()
            Qimg_PRAPic = image_PRAPic.toqimage()

            self.HeatmapLable.setScaledContents(True)#适应画布，保持分辨率
            self.PGEAPic.setScaledContents(True)
            self.SAHeatmapLable.setScaledContents(True)
            self.DHeatmapLable.setScaledContents(True)
            self.SAAPic.setScaledContents(True)
            self.PRAPic.setScaledContents(True)

            #scaredPixmap = image_PGEAPic.scaled(400, 400, aspectRatioMode=Qt.KeepAspectRatio)
            self.HeatmapLable.setPixmap(QtGui.QPixmap.fromImage(Qimg))#对应控件
            self.SAHeatmapLable.setPixmap(QtGui.QPixmap.fromImage(Qimg_SAHeatMap))
            self.PGEAPic.setPixmap(QtGui.QPixmap.fromImage(Qimg_PGEAPic))
            self.DHeatmapLable.setPixmap(QtGui.QPixmap.fromImage(Qimg_PRHeatMap))
            self.SAAPic.setPixmap(QtGui.QPixmap.fromImage(Qimg_SAAPic))
            self.PRAPic.setPixmap(QtGui.QPixmap.fromImage(Qimg_PRAPic))
