# Form implementation generated from reading ui file 'Function5.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pandas as pd
import numpy as np
import sys
import PIL
sys.path.append("..")
from PGE_Model import Heatmap
from PGE_Model import Relation
from PGE_Model import Score_Count
from PGE_Model import Linear_Regression
from PGE_Model import Random_Forest_Classifier_Predict

class Ui_Form5(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1032, 781)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1032, 781))
        self.scrollArea.setStyleSheet("border:transparent;\n"
"background-color:white;\n"
"QScrollBar {height:0px;width:0px;}")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1032, 3410))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(871, 3410))
        self.scrollAreaWidgetContents.setStyleSheet("QScrollBar {height:0px;width:0px;}")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(30, 20, 161, 51))
        self.label.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("font-size:40px;font:bold;")
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setGeometry(QtCore.QRect(30, 80, 971, 1))
        self.line.setStyleSheet("background-color:rgb(230,230,230);\n"
"max-height:5px;")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(20, 90, 991, 621))
        self.widget.setObjectName("widget")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 91, 16))
        self.label_6.setStyleSheet("color:rgb(53,120,246);font-size:10px;background-color:transparent;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 431, 31))
        self.label_7.setStyleSheet("background-color:transparent;color:rgb(40,40,40);font-size:20px")
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(690, 100, 261, 461))
        self.label_5.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.htmap = QtWidgets.QLabel(self.widget)
        self.htmap.setGeometry(QtCore.QRect(10, 70, 641, 541))
        self.htmap.setStyleSheet("border:2px solid rgb(53,120,246);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.htmap.setObjectName("htmap")
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_3.setGeometry(QtCore.QRect(20, 730, 991, 461))
        self.widget_3.setObjectName("widget_3")
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setGeometry(QtCore.QRect(10, 0, 91, 16))
        self.label_8.setStyleSheet("color:rgb(53,120,246);font-size:10px;background-color:transparent;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 221, 31))
        self.label_9.setStyleSheet("background-color:transparent;color:rgb(40,40,40);font-size:20px")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        self.label_10.setGeometry(QtCore.QRect(590, 150, 341, 221))
        self.label_10.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.frc = QtWidgets.QLabel(self.widget_3)
        self.frc.setGeometry(QtCore.QRect(10, 70, 511, 381))
        self.frc.setStyleSheet("border:2px solid rgb(53,120,246);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.frc.setObjectName("frc")
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setGeometry(QtCore.QRect(30, 720, 971, 1))
        self.line_2.setStyleSheet("background-color:rgb(230,230,230);\n"
"max-height:5px;")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setGeometry(QtCore.QRect(30, 1200, 971, 1))
        self.line_3.setStyleSheet("background-color:rgb(230,230,230);\n"
"max-height:5px;")
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.widget_9 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_9.setGeometry(QtCore.QRect(20, 1210, 991, 791))
        self.widget_9.setObjectName("widget_9")
        self.label_18 = QtWidgets.QLabel(self.widget_9)
        self.label_18.setGeometry(QtCore.QRect(10, 0, 91, 16))
        self.label_18.setStyleSheet("color:rgb(53,120,246);font-size:10px;background-color:transparent;")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.widget_9)
        self.label_19.setGeometry(QtCore.QRect(10, 20, 221, 31))
        self.label_19.setStyleSheet("background-color:transparent;color:rgb(40,40,40);font-size:20px")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.widget_9)
        self.label_20.setGeometry(QtCore.QRect(610, 130, 291, 221))
        self.label_20.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.label_20.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.widget_9)
        self.label_21.setGeometry(QtCore.QRect(80, 490, 291, 221))
        self.label_21.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.label_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.s1 = QtWidgets.QLabel(self.widget_9)
        self.s1.setGeometry(QtCore.QRect(10, 70, 491, 331))
        self.s1.setStyleSheet("border:2px solid rgb(53,120,246);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.s1.setObjectName("s1")
        self.s2 = QtWidgets.QLabel(self.widget_9)
        self.s2.setGeometry(QtCore.QRect(480, 440, 491, 331))
        self.s2.setStyleSheet("border:2px solid rgb(53,120,246);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.s2.setText("")
        self.s2.setObjectName("s2")
        self.widget_12 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_12.setGeometry(QtCore.QRect(20, 2000, 991, 731))
        self.widget_12.setObjectName("widget_12")
        self.label_24 = QtWidgets.QLabel(self.widget_12)
        self.label_24.setGeometry(QtCore.QRect(620, 70, 291, 221))
        self.label_24.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.label_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.widget_12)
        self.label_25.setGeometry(QtCore.QRect(80, 440, 291, 221))
        self.label_25.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.label_25.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.s3 = QtWidgets.QLabel(self.widget_12)
        self.s3.setGeometry(QtCore.QRect(10, 20, 491, 331))
        self.s3.setStyleSheet("border:2px solid rgb(53,120,246);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.s3.setObjectName("s3")
        self.s4 = QtWidgets.QLabel(self.widget_12)
        self.s4.setGeometry(QtCore.QRect(480, 390, 491, 331))
        self.s4.setStyleSheet("border:2px solid rgb(53,120,246);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.s4.setObjectName("s4")
        self.widget_5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_5.setGeometry(QtCore.QRect(20, 2750, 991, 631))
        self.widget_5.setObjectName("widget_5")
        self.label_14 = QtWidgets.QLabel(self.widget_5)
        self.label_14.setGeometry(QtCore.QRect(10, 0, 91, 16))
        self.label_14.setStyleSheet("color:rgb(53,120,246);font-size:10px;background-color:transparent;")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.widget_5)
        self.label_15.setGeometry(QtCore.QRect(10, 20, 291, 31))
        self.label_15.setStyleSheet("background-color:transparent;color:rgb(40,40,40);font-size:20px")
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.widget_5)
        self.label_17.setGeometry(QtCore.QRect(240, 480, 511, 131))
        self.label_17.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.rf1 = QtWidgets.QLabel(self.widget_5)
        self.rf1.setGeometry(QtCore.QRect(60, 80, 371, 361))
        self.rf1.setStyleSheet("border:2px solid rgb(53,120,246);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.rf1.setObjectName("rf1")
        self.rf2 = QtWidgets.QLabel(self.widget_5)
        self.rf2.setGeometry(QtCore.QRect(550, 80, 371, 361))
        self.rf2.setStyleSheet("border:2px solid rgb(53,120,246);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.rf2.setObjectName("rf2")
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setGeometry(QtCore.QRect(30, 3390, 971, 1))
        self.line_4.setStyleSheet("background-color:rgb(230,230,230);\n"
"max-height:5px;")
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setGeometry(QtCore.QRect(20, 2740, 971, 1))
        self.line_5.setStyleSheet("background-color:rgb(230,230,230);\n"
"max-height:5px;")
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "保送分析"))
        self.label_6.setText(_translate("Form", "热力图"))
        self.label_7.setText(_translate("Form", "通过保送要素热力图对保送情况进行初步分析"))
        self.label_5.setText(_translate("Form", "保研直博相关要素热力图分析\n"
"\n"
"最有可能影响保送的特征是学校等级\n"
"研习经历\n"
"\n"
"影响相对较小的特征是自身意愿和是\n"
"否有学术产物及本科绩点"))
        self.htmap.setText(_translate("Form", "TextLabel"))
        self.label_8.setText(_translate("Form", "分数统计"))
        self.label_9.setText(_translate("Form", "各分数段出现频次展示"))
        self.label_10.setText(_translate("Form", "可以看到，立志于保送的学生\n"
"其深造意向都非常高，大部分都是5\n"
"这是从热力图无法看出来的\n"
"也解释了为什么本组的深造意愿和各特征相关度都较低"))
        self.frc.setText(_translate("Form", "TextLabel"))
        self.label_18.setText(_translate("Form", "关系展示"))
        self.label_19.setText(_translate("Form", "展示各要素之间的关系"))
        self.label_20.setText(_translate("Form", "保送的学生中，优秀的本科院校是至关重要的\n"
"大部分保送学生都是985、211院校出生\n"
"这些优质高校手握更多的保送资格"))
        self.label_21.setText(_translate("Form", "本科均分在热力图中与成功保送相关度较低\n"
"但仔细分析可以发现\n"
"能够成功保送的本科均分一般都高"))
        self.s1.setText(_translate("Form", "TextLabel"))
        self.label_24.setText(_translate("Form", "不难看出\n"
"成功保送的学生四级成绩都非常优秀"))
        self.label_25.setText(_translate("Form", "大多数保送成功的学生都有做项目和实习的经验"))
        self.s3.setText(_translate("Form", "TextLabel"))
        self.s4.setText(_translate("Form", "TextLabel"))
        self.label_14.setText(_translate("Form", "回归模型"))
        self.label_15.setText(_translate("Form", "随机森林分类展示"))
        self.label_17.setText(_translate("Form", "在训练组样本中，随机森林模型实现了全部正确预测\n"
"在测试组样本中的表现同样优秀"))
        self.rf1.setText(_translate("Form", "TextLabel"))
        self.rf2.setText(_translate("Form", "TextLabel"))
        self.plot()
    def plot(self):
        dfPR = pd.read_csv('/Users/reeno/Documents/Achievement_Analysis/score/WSDPR_Ver1.1.csv',sep=',')

        ihtmap = Heatmap.Draw_HeatMap(dfPR)
        isc = Score_Count.Draw_PR(dfPR)
        is1 = Relation.Relation_btw_SUC_and_UR(dfPR)
        is2 = Relation.Relation_btw_SUC_and_CGPA(dfPR)
        is3 = Relation.Relation_btw_SUC_and_CET4(dfPR)
        is4 = Relation.Relation_btw_SUC_and_Res(dfPR)
        irf1 = Random_Forest_Classifier_Predict.Random_Forest_Classifier(dfPR,'dPR')
        irf2 = Random_Forest_Classifier_Predict.Random_Forest_Classifier(dfPR,'dPR1')

        Qhtmap = ihtmap.toqimage()#转换成qimage嵌入qt
        Qisc = isc.toqimage()
        Qis1 = is1.toqimage()
        Qis2 = is2.toqimage()
        Qis3 = is3.toqimage()
        Qis4 = is4.toqimage()

        Qirf1 = irf1.toqimage()
        Qirf2 = irf2.toqimage()

        self.htmap.setScaledContents(True)#适应画布，保持分辨率
        self.frc.setScaledContents(True)
        self.s1.setScaledContents(True)
        self.s2.setScaledContents(True)
        self.s3.setScaledContents(True)
        self.s4.setScaledContents(True)
        self.rf1.setScaledContents(True)
        self.rf2.setScaledContents(True)

        self.htmap.setPixmap(QtGui.QPixmap.fromImage(Qhtmap))#对应控件
        self.frc.setPixmap(QtGui.QPixmap.fromImage(Qisc))
        self.s1.setPixmap(QtGui.QPixmap.fromImage(Qis1))
        self.s2.setPixmap(QtGui.QPixmap.fromImage(Qis2))
        self.s3.setPixmap(QtGui.QPixmap.fromImage(Qis3))
        self.s4.setPixmap(QtGui.QPixmap.fromImage(Qis4))
        self.rf1.setPixmap(QtGui.QPixmap.fromImage(Qirf1))
        self.rf2.setPixmap(QtGui.QPixmap.fromImage(Qirf2))
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys. argv)
    Form = QtWidgets.QMainWindow()
    myUi = Ui_Form5()
    myUi.setupUi(Form)
    Form.show()
    sys. exit(app.exec())