# Form implementation generated from reading ui file 'Function2.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys
import pandas as pd
import numpy as np
import PIL
from PyQt6.QtWidgets import QApplication

sys.path.append("..")

class Ui_Form2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1032, 781)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1032, 781))
        self.scrollArea.setStyleSheet("border:transparent;\n"
"background-color:white;\n"
"QScrollBar {height:0px;width:0px;}")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -2319, 1032, 3100))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(1032, 3100))
        self.scrollAreaWidgetContents.setStyleSheet("QScrollBar {height:0px;width:0px;}")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(30, 20, 161, 51))
        self.label.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("font-size:40px;font:bold;")
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setGeometry(QtCore.QRect(30, 80, 971, 1))
        self.line.setStyleSheet("background-color:rgb(230,230,230);\n"
"max-height:5px;")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.CET4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.CET4.setGeometry(QtCore.QRect(250, 220, 261, 41))
        self.CET4.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.CET4.setObjectName("CET4")
        self.CET6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.CET6.setGeometry(QtCore.QRect(250, 290, 261, 41))
        self.CET6.setStyleSheet("\n"
"border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.CET6.setObjectName("CET6")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(270, 410, 113, 32))
        self.pushButton.setStyleSheet("QPushButton{background-color: rgb(242,242,242);border:1px rgb(225, 225, 225);border-radius:8px;padding:2px 4px;color:rgb(232,85,95);}\n"
"QPushButton:pressed{background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(232,85,95);}")
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(130, 220, 121, 41))
        self.label_2.setStyleSheet("background-color:transparent;color:rgb(39,39,39);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(130, 290, 121, 41))
        self.label_3.setStyleSheet("background-color:transparent;color:rgb(39,39,39);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(30, 160, 591, 341))
        self.label_4.setStyleSheet("border:2px solid rgb(232,85,95);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(710, 200, 261, 211))
        self.label_5.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(30, 90, 91, 16))
        self.label_6.setStyleSheet("color:rgb(232,85,95);font-size:10px;background-color:transparent;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(30, 110, 391, 31))
        self.label_7.setStyleSheet("background-color:transparent;color:rgb(40,40,40);font-size:20px")
        self.label_7.setObjectName("label_7")
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setGeometry(QtCore.QRect(30, 540, 971, 1))
        self.line_2.setStyleSheet("background-color:rgb(230,230,230);\n"
"max-height:5px;")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(40, 350, 101, 41))
        self.label_8.setStyleSheet("background-color:transparent;color:rgb(39,39,39);")
        self.label_8.setObjectName("label_8")
        self.CBOX92 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.CBOX92.setGeometry(QtCore.QRect(150, 360, 87, 20))
        self.CBOX92.setAutoExclusive(True)
        self.CBOX92.setObjectName("CBOX92")
        self.CBOXsyl = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.CBOXsyl.setGeometry(QtCore.QRect(240, 360, 87, 20))
        self.CBOXsyl.setAutoExclusive(True)
        self.CBOXsyl.setObjectName("CBOXsyl")
        self.CBOXyb = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.CBOXyb.setGeometry(QtCore.QRect(340, 360, 87, 20))
        self.CBOXyb.setAutoExclusive(True)
        self.CBOXyb.setObjectName("CBOXyb")
        self.CBOXbk = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.CBOXbk.setGeometry(QtCore.QRect(430, 360, 87, 20))
        self.CBOXbk.setAutoExclusive(True)
        self.CBOXbk.setObjectName("CBOXbk")
        self.CBOXzk = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.CBOXzk.setGeometry(QtCore.QRect(520, 360, 87, 20))
        self.CBOXzk.setAutoExclusive(True)
        self.CBOXzk.setObjectName("CBOXzk")
        self.label_9yc = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9yc.setGeometry(QtCore.QRect(30, 550, 91, 16))
        self.label_9yc.setStyleSheet("color:rgb(232,85,95);font-size:10px;background-color:transparent;")
        self.label_9yc.setObjectName("label_9yc")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setGeometry(QtCore.QRect(30, 570, 391, 31))
        self.label_10.setStyleSheet("background-color:transparent;color:rgb(40,40,40);font-size:20px")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(30, 620, 971, 891))
        self.label_11.setStyleSheet("border:2px solid rgb(232,85,95);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setGeometry(QtCore.QRect(100, 670, 71, 16))
        self.label_12.setStyleSheet("background-color:transparent;color:rgb(39,39,39);")
        self.label_12.setObjectName("label_12")
        self.math = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.math.setGeometry(QtCore.QRect(610, 660, 261, 41))
        self.math.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.math.setObjectName("math")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(530, 670, 71, 16))
        self.label_9.setStyleSheet("background-color:transparent;color:rgb(39,39,39);")
        self.label_9.setObjectName("label_9")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setGeometry(QtCore.QRect(100, 750, 71, 16))
        self.label_13.setStyleSheet("background-color:transparent;color:rgb(39,39,39);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setGeometry(QtCore.QRect(530, 750, 71, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setGeometry(QtCore.QRect(100, 830, 71, 16))
        self.label_15.setStyleSheet("background-color:transparent;color:rgb(39,39,39);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setGeometry(QtCore.QRect(530, 830, 71, 16))
        self.label_16.setStyleSheet("background-color:transparent;color:rgb(39,39,39);")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setGeometry(QtCore.QRect(60, 910, 111, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setGeometry(QtCore.QRect(490, 910, 111, 16))
        self.label_18.setStyleSheet("background-color:transparent;color:rgb(39,39,39);\n"
"")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setGeometry(QtCore.QRect(100, 990, 71, 16))
        self.label_19.setStyleSheet("background-color:transparent;color:rgb(39,39,39);")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setGeometry(QtCore.QRect(510, 990, 81, 16))
        self.label_20.setStyleSheet("background-color:transparent;color:rgb(39,39,39);")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setGeometry(QtCore.QRect(100, 1070, 81, 16))
        self.label_21.setStyleSheet("background-color:transparent;color:rgb(39,39,39);\n"
"")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_22.setGeometry(QtCore.QRect(520, 1070, 60, 16))
        self.label_22.setStyleSheet("background-color:transparent;color:rgb(39,39,39);\n"
"")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_23.setGeometry(QtCore.QRect(70, 1140, 101, 41))
        self.label_23.setStyleSheet("background-color:transparent;color:rgb(39,39,39);")
        self.label_23.setObjectName("label_23")
        self.score = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.score.setGeometry(QtCore.QRect(610, 740, 261, 41))
        self.score.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.score.setObjectName("score")
        self.CET4_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.CET4_2.setGeometry(QtCore.QRect(180, 820, 261, 41))
        self.CET4_2.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.CET4_2.setObjectName("CET4_2")
        self.eng = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.eng.setGeometry(QtCore.QRect(180, 740, 261, 41))
        self.eng.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.eng.setObjectName("eng")
        self.CET6_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.CET6_2.setGeometry(QtCore.QRect(610, 820, 261, 41))
        self.CET6_2.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.CET6_2.setObjectName("CET6_2")
        self.cl = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.cl.setGeometry(QtCore.QRect(610, 980, 261, 41))
        self.cl.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.cl.setObjectName("cl")
        self.gpa = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.gpa.setGeometry(QtCore.QRect(610, 1060, 261, 41))
        self.gpa.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.gpa.setObjectName("gpa")
        self.sl = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.sl.setGeometry(QtCore.QRect(180, 1060, 261, 41))
        self.sl.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.sl.setObjectName("sl")
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_25.setGeometry(QtCore.QRect(180, 660, 261, 41))
        self.label_25.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;\n"
"")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.szyx1 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.szyx1.setGeometry(QtCore.QRect(210, 670, 41, 20))
        self.szyx1.setStyleSheet("background-color : transparent")
        self.szyx1.setObjectName("szyx1")
        self.szyx2 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.szyx2.setGeometry(QtCore.QRect(250, 670, 41, 20))
        self.szyx2.setStyleSheet("background-color : transparent")
        self.szyx2.setObjectName("szyx2")
        self.szyx3 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.szyx3.setGeometry(QtCore.QRect(290, 670, 41, 20))
        self.szyx3.setStyleSheet("background-color : transparent")
        self.szyx3.setObjectName("szyx3")
        self.szyx4 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.szyx4.setGeometry(QtCore.QRect(330, 670, 41, 20))
        self.szyx4.setStyleSheet("background-color : transparent")
        self.szyx4.setObjectName("szyx4")
        self.szyx5 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.szyx5.setGeometry(QtCore.QRect(370, 670, 41, 20))
        self.szyx5.setStyleSheet("background-color : transparent")
        self.szyx5.setObjectName("szyx5")
        self.yxjl = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.yxjl.setGeometry(QtCore.QRect(180, 900, 261, 41))
        self.yxjl.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.yxjl.setObjectName("yxjl")
        self.yyxjl = QtWidgets.QRadioButton(self.yxjl)
        self.yyxjl.setGeometry(QtCore.QRect(20, 10, 101, 20))
        self.yyxjl.setStyleSheet("border:transparent;border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.yyxjl.setObjectName("yyxjl")
        self.wyxjl = QtWidgets.QRadioButton(self.yxjl)
        self.wyxjl.setGeometry(QtCore.QRect(130, 10, 101, 20))
        self.wyxjl.setStyleSheet("border:transparent;border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.wyxjl.setObjectName("wyxjl")
        self.ezyx = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.ezyx.setGeometry(QtCore.QRect(180, 980, 261, 41))
        self.ezyx.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.ezyx.setObjectName("ezyx")
        self.yezyx = QtWidgets.QRadioButton(self.ezyx)
        self.yezyx.setGeometry(QtCore.QRect(20, 10, 101, 20))
        self.yezyx.setStyleSheet("border:transparent;border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.yezyx.setObjectName("yezyx")
        self.wezyx = QtWidgets.QRadioButton(self.ezyx)
        self.wezyx.setGeometry(QtCore.QRect(130, 10, 101, 20))
        self.wezyx.setStyleSheet("border:transparent;border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.wezyx.setObjectName("wezyx")
        self.xszz = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.xszz.setGeometry(QtCore.QRect(610, 900, 261, 41))
        self.xszz.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.xszz.setObjectName("xszz")
        self.yxszz = QtWidgets.QRadioButton(self.xszz)
        self.yxszz.setGeometry(QtCore.QRect(20, 10, 101, 20))
        self.yxszz.setStyleSheet("border:transparent;border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.yxszz.setObjectName("yxszz")
        self.wxszz = QtWidgets.QRadioButton(self.xszz)
        self.wxszz.setGeometry(QtCore.QRect(130, 10, 101, 20))
        self.wxszz.setStyleSheet("border:transparent;border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.wxszz.setObjectName("wxszz")
        self.bkyx = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.bkyx.setGeometry(QtCore.QRect(180, 1130, 691, 80))
        self.bkyx.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.bkyx.setObjectName("bkyx")
        self.bk92 = QtWidgets.QRadioButton(self.bkyx)
        self.bk92.setGeometry(QtCore.QRect(20, 30, 121, 20))
        self.bk92.setStyleSheet("border:transparent;border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.bk92.setObjectName("bk92")
        self.bksyl = QtWidgets.QRadioButton(self.bkyx)
        self.bksyl.setGeometry(QtCore.QRect(160, 30, 111, 20))
        self.bksyl.setStyleSheet("border:transparent;border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.bksyl.setObjectName("bksyl")
        self.yb = QtWidgets.QRadioButton(self.bkyx)
        self.yb.setGeometry(QtCore.QRect(290, 30, 100, 20))
        self.yb.setStyleSheet("border:transparent;border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.yb.setObjectName("yb")
        self.bk = QtWidgets.QRadioButton(self.bkyx)
        self.bk.setGeometry(QtCore.QRect(420, 30, 100, 20))
        self.bk.setStyleSheet("border:transparent;border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.bk.setObjectName("bk")
        self.zk = QtWidgets.QRadioButton(self.bkyx)
        self.zk.setGeometry(QtCore.QRect(550, 30, 100, 20))
        self.zk.setStyleSheet("border:transparent;border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.zk.setObjectName("zk")
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(460, 1240, 113, 32))
        self.pushButton_2.setStyleSheet("QPushButton{background-color: rgb(242,242,242);border:1px rgb(225, 225, 225);border-radius:8px;padding:2px 4px;color:rgb(232,85,95);}\n"
"QPushButton:pressed{background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(232,85,95);}")
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.resltky = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.resltky.setGeometry(QtCore.QRect(250, 1300, 531, 151))
        self.resltky.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.resltky.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.resltky.setObjectName("resltky")
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setGeometry(QtCore.QRect(30, 1550, 971, 1))
        self.line_3.setStyleSheet("background-color:rgb(230,230,230);\n"
"max-height:5px;")
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24.setGeometry(QtCore.QRect(30, 1560, 91, 16))
        self.label_24.setStyleSheet("color:rgb(232,85,95);font-size:10px;background-color:transparent;")
        self.label_24.setObjectName("label_24")
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_26.setGeometry(QtCore.QRect(30, 1580, 391, 31))
        self.label_26.setStyleSheet("background-color:transparent;color:rgb(40,40,40);font-size:20px")
        self.label_26.setObjectName("label_26")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(30, 1630, 971, 651))
        self.widget.setStyleSheet("border:2px solid rgb(232,85,95);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(60, 20, 401, 71))
        self.widget_2.setStyleSheet("background-color:transparent;border:transparent")
        self.widget_2.setObjectName("widget_2")
        self.label_27 = QtWidgets.QLabel(self.widget_2)
        self.label_27.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_27.setObjectName("label_27")
        self.gre = QtWidgets.QLineEdit(self.widget_2)
        self.gre.setGeometry(QtCore.QRect(90, 20, 261, 41))
        self.gre.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.gre.setObjectName("gre")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(490, 20, 411, 71))
        self.widget_3.setStyleSheet("background-color:transparent;border:transparent")
        self.widget_3.setObjectName("widget_3")
        self.label_28 = QtWidgets.QLabel(self.widget_3)
        self.label_28.setGeometry(QtCore.QRect(0, 30, 91, 16))
        self.label_28.setObjectName("label_28")
        self.toefl = QtWidgets.QLineEdit(self.widget_3)
        self.toefl.setGeometry(QtCore.QRect(90, 20, 261, 41))
        self.toefl.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.toefl.setObjectName("toefl")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setGeometry(QtCore.QRect(60, 100, 411, 71))
        self.widget_4.setStyleSheet("background-color:transparent;border:transparent")
        self.widget_4.setObjectName("widget_4")
        self.label_30 = QtWidgets.QLabel(self.widget_4)
        self.label_30.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_30.setObjectName("label_30")
        self.gpalx = QtWidgets.QLineEdit(self.widget_4)
        self.gpalx.setGeometry(QtCore.QRect(90, 20, 261, 41))
        self.gpalx.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.gpalx.setObjectName("gpalx")
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setGeometry(QtCore.QRect(490, 100, 411, 71))
        self.widget_5.setStyleSheet("background-color:transparent;border:transparent")
        self.widget_5.setObjectName("widget_5")
        self.label_31 = QtWidgets.QLabel(self.widget_5)
        self.label_31.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.widget_5)
        self.label_32.setGeometry(QtCore.QRect(90, 20, 261, 41))
        self.label_32.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;\n"
"")
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.zsyy1lx = QtWidgets.QRadioButton(self.widget_5)
        self.zsyy1lx.setGeometry(QtCore.QRect(100, 30, 41, 20))
        self.zsyy1lx.setStyleSheet("background-color : transparent")
        self.zsyy1lx.setObjectName("zsyy1lx")
        self.zsyy2lx = QtWidgets.QRadioButton(self.widget_5)
        self.zsyy2lx.setGeometry(QtCore.QRect(150, 30, 41, 20))
        self.zsyy2lx.setStyleSheet("background-color : transparent")
        self.zsyy2lx.setObjectName("zsyy2lx")
        self.zsyy3lx = QtWidgets.QRadioButton(self.widget_5)
        self.zsyy3lx.setGeometry(QtCore.QRect(200, 30, 41, 20))
        self.zsyy3lx.setStyleSheet("background-color : transparent")
        self.zsyy3lx.setObjectName("zsyy3lx")
        self.zsyy4lx = QtWidgets.QRadioButton(self.widget_5)
        self.zsyy4lx.setGeometry(QtCore.QRect(250, 30, 41, 20))
        self.zsyy4lx.setStyleSheet("background-color : transparent")
        self.zsyy4lx.setObjectName("zsyy4lx")
        self.zsyy5lx = QtWidgets.QRadioButton(self.widget_5)
        self.zsyy5lx.setGeometry(QtCore.QRect(300, 30, 41, 20))
        self.zsyy5lx.setStyleSheet("background-color : transparent")
        self.zsyy5lx.setObjectName("zsyy5lx")
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setGeometry(QtCore.QRect(20, 180, 451, 71))
        self.widget_6.setStyleSheet("background-color:transparent;border:transparent")
        self.widget_6.setObjectName("widget_6")
        self.label_33 = QtWidgets.QLabel(self.widget_6)
        self.label_33.setGeometry(QtCore.QRect(40, 30, 91, 20))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.widget_6)
        self.label_34.setGeometry(QtCore.QRect(130, 20, 261, 41))
        self.label_34.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;\n"
"")
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.tjx1 = QtWidgets.QRadioButton(self.widget_6)
        self.tjx1.setGeometry(QtCore.QRect(140, 30, 41, 20))
        self.tjx1.setStyleSheet("background-color : transparent")
        self.tjx1.setObjectName("tjx1")
        self.tjx2 = QtWidgets.QRadioButton(self.widget_6)
        self.tjx2.setGeometry(QtCore.QRect(190, 30, 41, 20))
        self.tjx2.setStyleSheet("background-color : transparent")
        self.tjx2.setObjectName("tjx2")
        self.tjx3 = QtWidgets.QRadioButton(self.widget_6)
        self.tjx3.setGeometry(QtCore.QRect(240, 30, 41, 20))
        self.tjx3.setStyleSheet("background-color : transparent")
        self.tjx3.setObjectName("tjx3")
        self.tjx4 = QtWidgets.QRadioButton(self.widget_6)
        self.tjx4.setGeometry(QtCore.QRect(290, 30, 41, 20))
        self.tjx4.setStyleSheet("background-color : transparent")
        self.tjx4.setObjectName("tjx4")
        self.tjx5 = QtWidgets.QRadioButton(self.widget_6)
        self.tjx5.setGeometry(QtCore.QRect(340, 30, 41, 20))
        self.tjx5.setStyleSheet("background-color : transparent")
        self.tjx5.setObjectName("tjx5")
        self.widget_7 = QtWidgets.QWidget(self.widget)
        self.widget_7.setGeometry(QtCore.QRect(450, 180, 451, 71))
        self.widget_7.setStyleSheet("background-color:transparent;border:transparent")
        self.widget_7.setObjectName("widget_7")
        self.label_35 = QtWidgets.QLabel(self.widget_7)
        self.label_35.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.widget_7)
        self.label_36.setGeometry(QtCore.QRect(130, 20, 261, 41))
        self.label_36.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;\n"
"")
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.yyxjllx = QtWidgets.QRadioButton(self.widget_7)
        self.yyxjllx.setGeometry(QtCore.QRect(150, 30, 111, 20))
        self.yyxjllx.setStyleSheet("background-color : transparent")
        self.yyxjllx.setObjectName("yyxjllx")
        self.wyxjllx = QtWidgets.QRadioButton(self.widget_7)
        self.wyxjllx.setGeometry(QtCore.QRect(260, 30, 111, 20))
        self.wyxjllx.setStyleSheet("background-color : transparent")
        self.wyxjllx.setObjectName("wyxjllx")
        self.widget_8 = QtWidgets.QWidget(self.widget)
        self.widget_8.setGeometry(QtCore.QRect(20, 270, 891, 121))
        self.widget_8.setStyleSheet("background-color:transparent;border:transparent")
        self.widget_8.setObjectName("widget_8")
        self.label_37 = QtWidgets.QLabel(self.widget_8)
        self.label_37.setGeometry(QtCore.QRect(10, 40, 121, 16))
        self.label_37.setObjectName("label_37")
        self.bkyx_2 = QtWidgets.QWidget(self.widget_8)
        self.bkyx_2.setGeometry(QtCore.QRect(130, 10, 691, 80))
        self.bkyx_2.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.bkyx_2.setObjectName("bkyx_2")
        self.bk92lx = QtWidgets.QRadioButton(self.bkyx_2)
        self.bk92lx.setGeometry(QtCore.QRect(20, 30, 121, 20))
        self.bk92lx.setStyleSheet("border:transparent;border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.bk92lx.setObjectName("bk92lx")
        self.bksyllx = QtWidgets.QRadioButton(self.bkyx_2)
        self.bksyllx.setGeometry(QtCore.QRect(160, 30, 111, 20))
        self.bksyllx.setStyleSheet("border:transparent;border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.bksyllx.setObjectName("bksyllx")
        self.bkyblx = QtWidgets.QRadioButton(self.bkyx_2)
        self.bkyblx.setGeometry(QtCore.QRect(290, 30, 100, 20))
        self.bkyblx.setStyleSheet("border:transparent;border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.bkyblx.setObjectName("bkyblx")
        self.bklx = QtWidgets.QRadioButton(self.bkyx_2)
        self.bklx.setGeometry(QtCore.QRect(420, 30, 100, 20))
        self.bklx.setStyleSheet("border:transparent;border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.bklx.setObjectName("bklx")
        self.zklx = QtWidgets.QRadioButton(self.bkyx_2)
        self.zklx.setGeometry(QtCore.QRect(550, 30, 100, 20))
        self.zklx.setStyleSheet("border:transparent;border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.zklx.setObjectName("zklx")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(430, 390, 113, 32))
        self.pushButton_3.setStyleSheet("QPushButton{background-color: rgb(242,242,242);border:1px rgb(225, 225, 225);border-radius:8px;padding:2px 4px;color:rgb(232,85,95);}\n"
"QPushButton:pressed{background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(232,85,95);}")
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.resltlx = QtWidgets.QLabel(self.widget)
        self.resltlx.setGeometry(QtCore.QRect(220, 450, 531, 151))
        self.resltlx.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.resltlx.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.resltlx.setObjectName("resltlx")
        self.widget_9 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_9.setGeometry(QtCore.QRect(30, 2400, 971, 651))
        self.widget_9.setStyleSheet("border:2px solid rgb(232,85,95);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.widget_9.setObjectName("widget_9")
        self.widget_10 = QtWidgets.QWidget(self.widget_9)
        self.widget_10.setGeometry(QtCore.QRect(60, 20, 401, 71))
        self.widget_10.setStyleSheet("background-color:transparent;border:transparent")
        self.widget_10.setObjectName("widget_10")
        self.label_38 = QtWidgets.QLabel(self.widget_10)
        self.label_38.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_38.setObjectName("label_38")
        self.cet4bs = QtWidgets.QLineEdit(self.widget_10)
        self.cet4bs.setGeometry(QtCore.QRect(90, 20, 261, 41))
        self.cet4bs.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.cet4bs.setObjectName("cet4bs")
        self.widget_11 = QtWidgets.QWidget(self.widget_9)
        self.widget_11.setGeometry(QtCore.QRect(490, 20, 411, 71))
        self.widget_11.setStyleSheet("background-color:transparent;border:transparent")
        self.widget_11.setObjectName("widget_11")
        self.label_39 = QtWidgets.QLabel(self.widget_11)
        self.label_39.setGeometry(QtCore.QRect(0, 30, 91, 16))
        self.label_39.setObjectName("label_39")
        self.cet6bs = QtWidgets.QLineEdit(self.widget_11)
        self.cet6bs.setGeometry(QtCore.QRect(90, 20, 261, 41))
        self.cet6bs.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.cet6bs.setObjectName("cet6bs")
        self.widget_12 = QtWidgets.QWidget(self.widget_9)
        self.widget_12.setGeometry(QtCore.QRect(60, 100, 411, 71))
        self.widget_12.setStyleSheet("background-color:transparent;border:transparent")
        self.widget_12.setObjectName("widget_12")
        self.label_40 = QtWidgets.QLabel(self.widget_12)
        self.label_40.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_40.setObjectName("label_40")
        self.gpabs = QtWidgets.QLineEdit(self.widget_12)
        self.gpabs.setGeometry(QtCore.QRect(90, 20, 261, 41))
        self.gpabs.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.gpabs.setObjectName("gpabs")
        self.widget_13 = QtWidgets.QWidget(self.widget_9)
        self.widget_13.setGeometry(QtCore.QRect(490, 100, 411, 71))
        self.widget_13.setStyleSheet("background-color:transparent;border:transparent")
        self.widget_13.setObjectName("widget_13")
        self.label_41 = QtWidgets.QLabel(self.widget_13)
        self.label_41.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.widget_13)
        self.label_42.setGeometry(QtCore.QRect(90, 20, 261, 41))
        self.label_42.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;\n"
"")
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.zsyy1bs = QtWidgets.QRadioButton(self.widget_13)
        self.zsyy1bs.setGeometry(QtCore.QRect(100, 30, 41, 20))
        self.zsyy1bs.setStyleSheet("background-color : transparent")
        self.zsyy1bs.setObjectName("zsyy1bs")
        self.zsyy2bs = QtWidgets.QRadioButton(self.widget_13)
        self.zsyy2bs.setGeometry(QtCore.QRect(150, 30, 41, 20))
        self.zsyy2bs.setStyleSheet("background-color : transparent")
        self.zsyy2bs.setObjectName("zsyy2bs")
        self.zsyy3bs = QtWidgets.QRadioButton(self.widget_13)
        self.zsyy3bs.setGeometry(QtCore.QRect(200, 30, 41, 20))
        self.zsyy3bs.setStyleSheet("background-color : transparent")
        self.zsyy3bs.setObjectName("zsyy3bs")
        self.zsyy4bs = QtWidgets.QRadioButton(self.widget_13)
        self.zsyy4bs.setGeometry(QtCore.QRect(250, 30, 41, 20))
        self.zsyy4bs.setStyleSheet("background-color : transparent")
        self.zsyy4bs.setObjectName("zsyy4bs")
        self.zsyy5bs = QtWidgets.QRadioButton(self.widget_13)
        self.zsyy5bs.setGeometry(QtCore.QRect(300, 30, 41, 20))
        self.zsyy5bs.setStyleSheet("background-color : transparent")
        self.zsyy5bs.setObjectName("zsyy5bs")
        self.widget_15 = QtWidgets.QWidget(self.widget_9)
        self.widget_15.setGeometry(QtCore.QRect(450, 180, 451, 71))
        self.widget_15.setStyleSheet("background-color:transparent;border:transparent")
        self.widget_15.setObjectName("widget_15")
        self.label_45 = QtWidgets.QLabel(self.widget_15)
        self.label_45.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.widget_15)
        self.label_46.setGeometry(QtCore.QRect(130, 20, 261, 41))
        self.label_46.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;\n"
"")
        self.label_46.setText("")
        self.label_46.setObjectName("label_46")
        self.yyxjlbs = QtWidgets.QRadioButton(self.widget_15)
        self.yyxjlbs.setGeometry(QtCore.QRect(150, 30, 111, 20))
        self.yyxjlbs.setStyleSheet("background-color : transparent")
        self.yyxjlbs.setObjectName("yyxjlbs")
        self.wyxjlbs = QtWidgets.QRadioButton(self.widget_15)
        self.wyxjlbs.setGeometry(QtCore.QRect(260, 30, 111, 20))
        self.wyxjlbs.setStyleSheet("background-color : transparent")
        self.wyxjlbs.setObjectName("wyxjlbs")
        self.widget_16 = QtWidgets.QWidget(self.widget_9)
        self.widget_16.setGeometry(QtCore.QRect(20, 270, 891, 121))
        self.widget_16.setStyleSheet("background-color:transparent;border:transparent")
        self.widget_16.setObjectName("widget_16")
        self.label_47 = QtWidgets.QLabel(self.widget_16)
        self.label_47.setGeometry(QtCore.QRect(10, 40, 121, 16))
        self.label_47.setObjectName("label_47")
        self.bkyx_3 = QtWidgets.QWidget(self.widget_16)
        self.bkyx_3.setGeometry(QtCore.QRect(130, 10, 691, 80))
        self.bkyx_3.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.bkyx_3.setObjectName("bkyx_3")
        self.bk92bs = QtWidgets.QRadioButton(self.bkyx_3)
        self.bk92bs.setGeometry(QtCore.QRect(20, 30, 121, 20))
        self.bk92bs.setStyleSheet("border:transparent;border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.bk92bs.setObjectName("bk92bs")
        self.bksylbs = QtWidgets.QRadioButton(self.bkyx_3)
        self.bksylbs.setGeometry(QtCore.QRect(160, 30, 111, 20))
        self.bksylbs.setStyleSheet("border:transparent;border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.bksylbs.setObjectName("bksylbs")
        self.ybbs = QtWidgets.QRadioButton(self.bkyx_3)
        self.ybbs.setGeometry(QtCore.QRect(290, 30, 100, 20))
        self.ybbs.setStyleSheet("border:transparent;border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.ybbs.setObjectName("ybbs")
        self.bkbs = QtWidgets.QRadioButton(self.bkyx_3)
        self.bkbs.setGeometry(QtCore.QRect(420, 30, 100, 20))
        self.bkbs.setStyleSheet("border:transparent;border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.bkbs.setObjectName("bkbs")
        self.zkbs = QtWidgets.QRadioButton(self.bkyx_3)
        self.zkbs.setGeometry(QtCore.QRect(550, 30, 100, 20))
        self.zkbs.setStyleSheet("border:transparent;border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;")
        self.zkbs.setObjectName("zkbs")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_4.setGeometry(QtCore.QRect(430, 390, 113, 32))
        self.pushButton_4.setStyleSheet("QPushButton{background-color: rgb(242,242,242);border:1px rgb(225, 225, 225);border-radius:8px;padding:2px 4px;color:rgb(232,85,95);}\n"
"QPushButton:pressed{background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(232,85,95);}")
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.resltbs = QtWidgets.QLabel(self.widget_9)
        self.resltbs.setGeometry(QtCore.QRect(220, 450, 531, 151))
        self.resltbs.setStyleSheet("background-color:rgb(209, 207, 208);border:1px rgb(209, 207, 208);border-radius:8px;padding:2px 4px;color:rgb(68,68,68);")
        self.resltbs.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.resltbs.setObjectName("resltbs")
        self.widget_17 = QtWidgets.QWidget(self.widget_9)
        self.widget_17.setGeometry(QtCore.QRect(20, 180, 451, 71))
        self.widget_17.setStyleSheet("background-color:transparent;border:transparent")
        self.widget_17.setObjectName("widget_17")
        self.label_50 = QtWidgets.QLabel(self.widget_17)
        self.label_50.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.widget_17)
        self.label_51.setGeometry(QtCore.QRect(130, 20, 261, 41))
        self.label_51.setStyleSheet("border:2px solid rgb(209,207,208);border-radius:8px;\n"
"padding:2px 4px;color:rgb(68,68,68);\n"
"background-color:transparent;\n"
"")
        self.label_51.setText("")
        self.label_51.setObjectName("label_51")
        self.yxszzbs = QtWidgets.QRadioButton(self.widget_17)
        self.yxszzbs.setGeometry(QtCore.QRect(150, 30, 111, 20))
        self.yxszzbs.setStyleSheet("background-color : transparent")
        self.yxszzbs.setObjectName("yxszzbs")
        self.wxszzbs = QtWidgets.QRadioButton(self.widget_17)
        self.wxszzbs.setGeometry(QtCore.QRect(260, 30, 111, 20))
        self.wxszzbs.setStyleSheet("background-color : transparent")
        self.wxszzbs.setObjectName("wxszzbs")
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setGeometry(QtCore.QRect(30, 2320, 971, 1))
        self.line_4.setStyleSheet("background-color:rgb(230,230,230);\n"
"max-height:5px;")
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_48 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_48.setGeometry(QtCore.QRect(30, 2330, 91, 16))
        self.label_48.setStyleSheet("color:rgb(232,85,95);font-size:10px;background-color:transparent;")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_49.setGeometry(QtCore.QRect(30, 2350, 391, 31))
        self.label_49.setStyleSheet("background-color:transparent;color:rgb(40,40,40);font-size:20px")
        self.label_49.setObjectName("label_49")
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setGeometry(QtCore.QRect(30, 3080, 971, 1))
        self.line_5.setStyleSheet("background-color:rgb(230,230,230);\n"
"max-height:5px;")
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_4.raise_()
        self.label.raise_()
        self.line.raise_()
        self.CET4.raise_()
        self.CET6.raise_()
        self.pushButton.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.line_2.raise_()
        self.label_8.raise_()
        self.CBOX92.raise_()
        self.CBOXsyl.raise_()
        self.CBOXyb.raise_()
        self.CBOXbk.raise_()
        self.CBOXzk.raise_()
        self.label_9yc.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.math.raise_()
        self.label_9.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.score.raise_()
        self.CET4_2.raise_()
        self.eng.raise_()
        self.CET6_2.raise_()
        self.cl.raise_()
        self.gpa.raise_()
        self.sl.raise_()
        self.label_25.raise_()
        self.szyx1.raise_()
        self.szyx2.raise_()
        self.szyx3.raise_()
        self.szyx4.raise_()
        self.szyx5.raise_()
        self.yxjl.raise_()
        self.ezyx.raise_()
        self.xszz.raise_()
        self.bkyx.raise_()
        self.pushButton_2.raise_()
        self.resltky.raise_()
        self.line_3.raise_()
        self.label_24.raise_()
        self.label_26.raise_()
        self.widget.raise_()
        self.widget_9.raise_()
        self.line_4.raise_()
        self.label_48.raise_()
        self.label_49.raise_()
        self.line_5.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.pushButton.clicked.connect(lambda :self.CalENG())
        self.pushButton_2.clicked.connect(lambda :self.PGEP())
        self.pushButton_3.clicked.connect(lambda :self.PSA())
        self.pushButton_4.clicked.connect(lambda :self.PRP())

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "成绩预测"))
        self.pushButton.setText(_translate("Form", "提交"))
        self.label_2.setText(_translate("Form", "请输入CET4成绩:"))
        self.label_3.setText(_translate("Form", "请输入CET6成绩:"))
        self.label_5.setText(_translate("Form", "利用线性回归模型\n"
"\n"
"通过四六级成绩对考研英语进行预测\n"
"\n"
"结果仅供参考"))
        self.label_6.setText(_translate("Form", "考研英语预测"))
        self.label_7.setText(_translate("Form", "通过四六级成绩对考研英语成绩进行推算"))
        self.label_8.setText(_translate("Form", "请选择本科院校:"))
        self.CBOX92.setText(_translate("Form", "985、211"))
        self.CBOXsyl.setText(_translate("Form", "双一流院校"))
        self.CBOXyb.setText(_translate("Form", "一本院校"))
        self.CBOXbk.setText(_translate("Form", "本科院校"))
        self.CBOXzk.setText(_translate("Form", "专科院校"))
        self.label_9yc.setText(_translate("Form", "考研上岸预测"))
        self.label_10.setText(_translate("Form", "通过考研成绩结合往年情况进行上岸预测"))
        self.label_12.setText(_translate("Form", "深造意愿:"))
        self.label_9.setText(_translate("Form", "数学分数:"))
        self.label_13.setText(_translate("Form", "英语分数:"))
        self.label_14.setText(_translate("Form", "考研总分:"))
        self.label_15.setText(_translate("Form", "四级分数:"))
        self.label_16.setText(_translate("Form", "六级分数:"))
        self.label_17.setText(_translate("Form", "是否有研习经历:"))
        self.label_18.setText(_translate("Form", "是否有学术著作:"))
        self.label_19.setText(_translate("Form", "二战意向:"))
        self.label_20.setText(_translate("Form", "往年国家线:"))
        self.label_21.setText(_translate("Form", "往年院线:"))
        self.label_22.setText(_translate("Form", "本科绩点:"))
        self.label_23.setText(_translate("Form", "请选择本科院校:"))
        self.szyx1.setText(_translate("Form", "1"))
        self.szyx2.setText(_translate("Form", "2"))
        self.szyx3.setText(_translate("Form", "3"))
        self.szyx4.setText(_translate("Form", "4"))
        self.szyx5.setText(_translate("Form", "5"))
        self.yyxjl.setText(_translate("Form", "有研习经历"))
        self.wyxjl.setText(_translate("Form", "无研习经历"))
        self.yezyx.setText(_translate("Form", "有二战意向"))
        self.wezyx.setText(_translate("Form", "无二战意向"))
        self.yxszz.setText(_translate("Form", "有学术著作"))
        self.wxszz.setText(_translate("Form", "无学术著作"))
        self.bk92.setText(_translate("Form", "985、211院校"))
        self.bksyl.setText(_translate("Form", "双一流院校"))
        self.yb.setText(_translate("Form", "一本院校"))
        self.bk.setText(_translate("Form", "本科院校"))
        self.zk.setText(_translate("Form", "专科院校"))
        self.pushButton_2.setText(_translate("Form", "提交"))
        self.resltky.setText(_translate("Form", "利用随机森林分类模型\n"
"\n"
"通过相关成绩对考研上岸进行预测\n"
"\n"
"结果仅供参考"))
        self.label_24.setText(_translate("Form", "留学预测"))
        self.label_26.setText(_translate("Form", "通过留学相关要素进行预测"))
        self.label_27.setText(_translate("Form", "GRE分数:"))
        self.label_28.setText(_translate("Form", "TOEFL分数:"))
        self.label_30.setText(_translate("Form", "本科绩点:"))
        self.label_31.setText(_translate("Form", "自身意愿:"))
        self.zsyy1lx.setText(_translate("Form", "1"))
        self.zsyy2lx.setText(_translate("Form", "2"))
        self.zsyy3lx.setText(_translate("Form", "3"))
        self.zsyy4lx.setText(_translate("Form", "4"))
        self.zsyy5lx.setText(_translate("Form", "5"))
        self.label_33.setText(_translate("Form", "推荐信力度:"))
        self.tjx1.setText(_translate("Form", "1"))
        self.tjx2.setText(_translate("Form", "2"))
        self.tjx3.setText(_translate("Form", "3"))
        self.tjx4.setText(_translate("Form", "4"))
        self.tjx5.setText(_translate("Form", "5"))
        self.label_35.setText(_translate("Form", "是否有研习经历:"))
        self.yyxjllx.setText(_translate("Form", "有研习经历"))
        self.wyxjllx.setText(_translate("Form", "无研习经历"))
        self.label_37.setText(_translate("Form", "请选择本科院校："))
        self.bk92lx.setText(_translate("Form", "985、211院校"))
        self.bksyllx.setText(_translate("Form", "双一流院校"))
        self.bkyblx.setText(_translate("Form", "一本院校"))
        self.bklx.setText(_translate("Form", "本科院校"))
        self.zklx.setText(_translate("Form", "专科院校"))
        self.pushButton_3.setText(_translate("Form", "提交"))
        self.resltlx.setText(_translate("Form", "利用随机森林分类模型\n"
"\n"
"通过相关成绩进行预测\n"
"\n"
"结果仅供参考"))
        self.label_38.setText(_translate("Form", "四级分数:"))
        self.label_39.setText(_translate("Form", "六级分数:"))
        self.label_40.setText(_translate("Form", "本科绩点:"))
        self.label_41.setText(_translate("Form", "自身意愿:"))
        self.zsyy1bs.setText(_translate("Form", "1"))
        self.zsyy2bs.setText(_translate("Form", "2"))
        self.zsyy3bs.setText(_translate("Form", "3"))
        self.zsyy4bs.setText(_translate("Form", "4"))
        self.zsyy5bs.setText(_translate("Form", "5"))
        self.label_45.setText(_translate("Form", "是否有研习经历:"))
        self.yyxjlbs.setText(_translate("Form", "有研习经历"))
        self.wyxjlbs.setText(_translate("Form", "无研习经历"))
        self.label_47.setText(_translate("Form", "请选择本科院校："))
        self.bk92bs.setText(_translate("Form", "985、211院校"))
        self.bksylbs.setText(_translate("Form", "双一流院校"))
        self.ybbs.setText(_translate("Form", "一本院校"))
        self.bkbs.setText(_translate("Form", "本科院校"))
        self.zkbs.setText(_translate("Form", "专科院校"))
        self.pushButton_4.setText(_translate("Form", "提交"))
        self.resltbs.setText(_translate("Form", "利用随机森林分类模型\n"
"\n"
"通过在校成绩对保送进行预测\n"
"\n"
"结果仅供参考"))
        self.label_50.setText(_translate("Form", "是否有学术著作:"))
        self.yxszzbs.setText(_translate("Form", "有学术著作"))
        self.wxszzbs.setText(_translate("Form", "无学术著作"))
        self.label_48.setText(_translate("Form", "保送预测"))
        self.label_49.setText(_translate("Form", "通过在校相关要素进行保送预测"))

    def CalENG(self):
        #print('1')
        inCET4 = self.CET4.text()
        inCET6 = self.CET6.text()

        check_box1_status = self.CBOX92.isChecked()
        check_box2_status = self.CBOXsyl.isChecked()
        check_box3_status = self.CBOXyb.isChecked()
        check_box4_status = self.CBOXbk.isChecked()
        check_box5_status = self.CBOXzk.isChecked()
        if(check_box1_status == True):level = 5
        elif(check_box2_status == True):level = 4
        elif(check_box3_status == True):level = 3
        elif(check_box4_status == True):level = 2
        elif(check_box5_status == True):level = 1
        else:level = 0

        dfPGE = pd.read_csv("/Users/reeno/Documents/Achievement_Analysis/Score/WPGE_Ver1.32.csv", sep =",")
        from PGE_Model import Linear_Regression
        if(int(inCET4) >= 220 and int(inCET4) <= 750 and int(inCET6) >= 220 and int(inCET6) <= 750 and level != 0):
                score = Linear_Regression.Linear_Regression(dfPGE,'PGE',inCET4,inCET6,level)
                self.label_5.setText('预测结果为'+score[1:5]+'分')
        elif(int(inCET4) < 220 or int(inCET4) > 750):
                self.label_5.setText('请输入正确的四级分数')
        elif(int(inCET6) < 220 or int(inCET6) > 750):
                self.label_5.setText('请输入正确的六级分数')
        else:
                self.label_5.setText('请选择院校')
    def PGEP(self):
        #输入框
        inCET4 = self.CET4_2.text()
        inCET6 = self.CET6_2.text()
        inscore = self.score.text()
        inmath = self.math.text()
        ineng = self.eng.text()
        incl = self.cl.text()
        insl = self.sl.text()
        ingpa = self.gpa.text()
        DV2CL = int(inscore) - int(incl)
        DV2SL = int(inscore) - int(insl)

        #考研本科
        check_box1_status = self.bk92.isChecked()
        check_box2_status = self.bksyl.isChecked()
        check_box3_status = self.yb.isChecked()
        check_box4_status = self.bk.isChecked()
        check_box5_status = self.zk.isChecked()
        if(check_box1_status == True):level = 5
        elif(check_box2_status == True):level = 4
        elif(check_box3_status == True):level = 3
        elif(check_box4_status == True):level = 2
        elif(check_box5_status == True):level = 1
        else:level = 0

        #深造意愿
        szyy_box1_status = self.szyx1.isChecked()
        szyy_box2_status = self.szyx2.isChecked()
        szyy_box3_status = self.szyx3.isChecked()
        szyy_box4_status = self.szyx4.isChecked()
        szyy_box5_status = self.szyx5.isChecked()
        if(szyy_box1_status == True):szyxlevel = 1
        elif(szyy_box2_status == True):szyxlevel = 2
        elif(szyy_box3_status == True):szyxlevel = 3
        elif(szyy_box4_status == True):szyxlevel = 4
        elif(szyy_box5_status == True):szyxlevel = 5
        else:szyxlevel = 0

        #研习经历
        yxjl_box1_status = self.yyxjl.isChecked()
        yxjl_box2_status = self.wyxjl.isChecked()
        if(yxjl_box1_status == True):yxjl = 1
        else:yxjl = 0

        #学术著作
        xszz_box1_status = self.yxszz.isChecked()
        xszz_box2_status = self.wxszz.isChecked()
        if(xszz_box1_status == True):xszz = 1
        else:xszz = 0

        #二战意向
        ezyx_box1_status = self.yezyx.isChecked()
        ezyx_box2_status = self.wezyx.isChecked()
        if(ezyx_box1_status == True):ezyx = 1
        else:ezyx = 0


        dfPGE = pd.read_csv("/Users/reeno/Documents/Achievement_Analysis/Score/WPGE_Ver1.32.csv", sep =",")
        from PGE_Model import Random_Forest_Classifier_Predict
        if(int(inCET4) >= 220 and int(inCET4) <= 750 and int(inCET6) >= 220 and int(inCET6) <= 750 and level != 0):
            result = Random_Forest_Classifier_Predict.predict_PGE(dfPGE,inCET4,inCET6,level,szyxlevel,inmath,ineng,inscore,ezyx,yxjl,xszz,ingpa,DV2CL,DV2SL)
            result = result[1]
            #print(result)
            if(result == '0'):result = '可能还需努力'
            else:result = '很有可能上岸，请继续努力'
            self.resltky.setText('预测结果为：'+result)
        elif(int(inCET4) < 220 or int(inCET4) > 750):
            self.resltky.setText('请输入正确的四级分数')
        elif(int(inCET6) < 220 or int(inCET6) > 750):
            self.resltky.setText('请输入正确的六级分数')
        else:
            self.resltky.setText('请检查输入')
    def PSA(self):
        #print('1')
        GRE = self.gre.text()
        TOEFL = self.toefl.text()
        CGPA = self.gpalx.text()
        CGPA = int(CGPA)*2.5

        #留学本科
        check_box1_status = self.bk92lx.isChecked()
        check_box2_status = self.bksyllx.isChecked()
        check_box3_status = self.bkyblx.isChecked()
        check_box4_status = self.bklx.isChecked()
        check_box5_status = self.zklx.isChecked()
        if(check_box1_status == True):level = 5
        elif(check_box2_status == True):level = 4
        elif(check_box3_status == True):level = 3
        elif(check_box4_status == True):level = 2
        elif(check_box5_status == True):level = 1
        else:level = 0

        #研习经历
        yxjl_box1_status = self.yyxjllx.isChecked()
        yxjl_box2_status = self.wyxjllx.isChecked()
        if(yxjl_box1_status == True):yxjl = 1
        else:yxjl = 0

        #推荐信
        tjx_box1_status = self.tjx1.isChecked()
        tjx_box2_status = self.tjx2.isChecked()
        tjx_box3_status = self.tjx3.isChecked()
        tjx_box4_status = self.tjx4.isChecked()
        tjx_box5_status = self.tjx5.isChecked()
        if(tjx_box1_status == True):tjxlv = 1
        elif(tjx_box2_status == True):tjxlv = 2
        elif(tjx_box3_status == True):tjxlv = 3
        elif(tjx_box4_status == True):tjxlv = 4
        elif(tjx_box5_status == True):tjxlv = 5
        else:tjxlv = 0

        #自身意愿
        zsyy_box1_status = self.zsyy1lx.isChecked()
        zsyy_box2_status = self.zsyy2lx.isChecked()
        zsyy_box3_status = self.zsyy3lx.isChecked()
        zsyy_box4_status = self.zsyy4lx.isChecked()
        zsyy_box5_status = self.zsyy5lx.isChecked()
        if(zsyy_box1_status == True):zsyylevel = 1
        elif(zsyy_box2_status == True):zsyylevel = 2
        elif(zsyy_box3_status == True):zsyylevel = 3
        elif(zsyy_box4_status == True):zsyylevel = 4
        elif(zsyy_box5_status == True):zsyylevel = 5
        else:zsyylevel = 0

        dfSA = pd.read_csv('/Users/reeno/Documents/Achievement_Analysis/score/Admission_Predict.csv',sep=',')
        from PGE_Model import Random_Forest_Classifier_Predict
        if(level != 0  and tjxlv != 0):
            result = Random_Forest_Classifier_Predict.predict_SA(dfSA,GRE,TOEFL,level,zsyylevel,tjxlv,yxjl,CGPA)
            result = result[1]
            #print(result)
            if(result == '0'):result = '可能还需努力'
            else:result = '很有可能，请继续努力'
            self.resltlx.setText('预测结果为：'+result)
        else:
            self.resltlx.setText('请检查输入')
    def PRP(self):
        #print('1')
        CET4 = self.cet4bs.text()
        CET6 = self.cet6bs.text()
        CGPA = self.gpabs.text()


        #保送本科
        check_box1_status = self.bk92bs.isChecked()
        check_box2_status = self.bksylbs.isChecked()
        check_box3_status = self.ybbs.isChecked()
        check_box4_status = self.bkbs.isChecked()
        check_box5_status = self.zkbs.isChecked()
        if(check_box1_status == True):level = 5
        elif(check_box2_status == True):level = 4
        elif(check_box3_status == True):level = 3
        elif(check_box4_status == True):level = 2
        elif(check_box5_status == True):level = 1
        else:level = 0

        #研习经历
        yxjl_box1_status = self.yyxjlbs.isChecked()
        yxjl_box2_status = self.wyxjlbs.isChecked()
        if(yxjl_box1_status == True):yxjl = 1
        else:yxjl = 0

        #学术产物
        xscw_box1_status = self.yxszzbs.isChecked()
        xscw_box2_status = self.wxszzbs.isChecked()
        if(xscw_box1_status == True):xscw = 1
        else:xscw = 0

        #自身意愿
        zsyy_box1_status = self.zsyy1bs.isChecked()
        zsyy_box2_status = self.zsyy2bs.isChecked()
        zsyy_box3_status = self.zsyy3bs.isChecked()
        zsyy_box4_status = self.zsyy4bs.isChecked()
        zsyy_box5_status = self.zsyy5bs.isChecked()
        if(zsyy_box1_status == True):zsyylevel = 1
        elif(zsyy_box2_status == True):zsyylevel = 2
        elif(zsyy_box3_status == True):zsyylevel = 3
        elif(zsyy_box4_status == True):zsyylevel = 4
        elif(zsyy_box5_status == True):zsyylevel = 5
        else:zsyylevel = 0

        dfPR = pd.read_csv('/Users/reeno/Documents/Achievement_Analysis/score/WSDPR_Ver1.1.csv',sep=',')
        from PGE_Model import Random_Forest_Classifier_Predict
        if(level != 0  and zsyylevel != 0):
            result = Random_Forest_Classifier_Predict.predict_PR(dfPR,CET4,CET6,level,zsyylevel,yxjl,CGPA,xscw)
            result = result[1]
            #print(result)
            if(result == '0'):result = '可能还需努力'
            else:result = '很有可能，请继续努力'
            self.resltbs.setText('预测结果为：'+result)
        else:
            self.resltbs.setText('请检查输入')

